version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: demo_aa
      POSTGRES_PASSWORD: demo_aa # Secure it!! This is an example
  local-demo.activeadmin.info:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://db/demo_aa_test
      DATABASE_USERNAME: demo_aa
      DATABASE_PASSWORD: demo_aa # Secure it!! This is an example
  test:
    build: .
    depends_on:
      - local-demo.activeadmin.info
    environment:
      app_endpoint: http://local-demo.activeadmin.info:3000